/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Candle = IDL.Record({
  'low' : IDL.Float64,
  'high' : IDL.Float64,
  'close' : IDL.Float64,
  'open' : IDL.Float64,
  'volume' : IDL.Float64,
  'timestamp' : IDL.Int,
  'symbol' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'telegramBotToken' : IDL.Text,
  'balance' : IDL.Float64,
  'dailyProfitTarget' : IDL.Float64,
  'maxRiskPercent' : IDL.Float64,
  'soundAlertsEnabled' : IDL.Bool,
  'telegramChatId' : IDL.Text,
});
export const Trade = IDL.Record({
  'sl' : IDL.Float64,
  'tp' : IDL.Float64,
  'pnl' : IDL.Float64,
  'probability' : IDL.Nat,
  'direction' : IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
  'entry' : IDL.Float64,
  'rrRatio' : IDL.Float64,
  'timestamp' : IDL.Int,
  'outcome' : IDL.Variant({
    'win' : IDL.Null,
    'pending' : IDL.Null,
    'loss' : IDL.Null,
  }),
  'lotSize' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const TradingViewData = IDL.Record({
  'value' : IDL.Text,
  'indicator' : IDL.Text,
});
export const TradingGoals = IDL.Record({
  'monthlyProfit' : IDL.Float64,
  'dailyProfit' : IDL.Float64,
});
export const AdvancedRiskSettings = IDL.Record({
  'maxConcurrentTrades' : IDL.Nat,
  'maxDailyLoss' : IDL.Float64,
});
export const Strategy = IDL.Variant({
  'scalping' : IDL.Null,
  'trendFollowing' : IDL.Null,
  'swing' : IDL.Null,
});
export const ExtendedProfile = IDL.Record({
  'telegramBotToken' : IDL.Text,
  'tradingViewData' : IDL.Vec(TradingViewData),
  'tradingGoals' : TradingGoals,
  'username' : IDL.Text,
  'balance' : IDL.Float64,
  'riskPercentage' : IDL.Float64,
  'soundAlertsEnabled' : IDL.Bool,
  'telegramChatId' : IDL.Text,
  'advancedRiskSettings' : AdvancedRiskSettings,
  'strategies' : IDL.Vec(Strategy),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateCandles' : IDL.Func([IDL.Text, IDL.Vec(Candle)], [], []),
  'addPair' : IDL.Func(
      [IDL.Text, IDL.Variant({ 'forex' : IDL.Null, 'crypto' : IDL.Null })],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'fetchBinanceData' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandles' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Vec(Candle)], ['query']),
  'getLatestTradeEntries' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Opt(Trade)))],
      ['query'],
    ),
  'getPairs' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(
            IDL.Text,
            IDL.Record({
              'type' : IDL.Variant({ 'forex' : IDL.Null, 'crypto' : IDL.Null }),
              'symbol' : IDL.Text,
            }),
          )
        ),
      ],
      ['query'],
    ),
  'getProfile' : IDL.Func([], [IDL.Opt(ExtendedProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'receiveMT5Candles' : IDL.Func([IDL.Text, IDL.Vec(Candle)], [], []),
  'removePair' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProfile' : IDL.Func([ExtendedProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Candle = IDL.Record({
    'low' : IDL.Float64,
    'high' : IDL.Float64,
    'close' : IDL.Float64,
    'open' : IDL.Float64,
    'volume' : IDL.Float64,
    'timestamp' : IDL.Int,
    'symbol' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'telegramBotToken' : IDL.Text,
    'balance' : IDL.Float64,
    'dailyProfitTarget' : IDL.Float64,
    'maxRiskPercent' : IDL.Float64,
    'soundAlertsEnabled' : IDL.Bool,
    'telegramChatId' : IDL.Text,
  });
  const Trade = IDL.Record({
    'sl' : IDL.Float64,
    'tp' : IDL.Float64,
    'pnl' : IDL.Float64,
    'probability' : IDL.Nat,
    'direction' : IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
    'entry' : IDL.Float64,
    'rrRatio' : IDL.Float64,
    'timestamp' : IDL.Int,
    'outcome' : IDL.Variant({
      'win' : IDL.Null,
      'pending' : IDL.Null,
      'loss' : IDL.Null,
    }),
    'lotSize' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const TradingViewData = IDL.Record({
    'value' : IDL.Text,
    'indicator' : IDL.Text,
  });
  const TradingGoals = IDL.Record({
    'monthlyProfit' : IDL.Float64,
    'dailyProfit' : IDL.Float64,
  });
  const AdvancedRiskSettings = IDL.Record({
    'maxConcurrentTrades' : IDL.Nat,
    'maxDailyLoss' : IDL.Float64,
  });
  const Strategy = IDL.Variant({
    'scalping' : IDL.Null,
    'trendFollowing' : IDL.Null,
    'swing' : IDL.Null,
  });
  const ExtendedProfile = IDL.Record({
    'telegramBotToken' : IDL.Text,
    'tradingViewData' : IDL.Vec(TradingViewData),
    'tradingGoals' : TradingGoals,
    'username' : IDL.Text,
    'balance' : IDL.Float64,
    'riskPercentage' : IDL.Float64,
    'soundAlertsEnabled' : IDL.Bool,
    'telegramChatId' : IDL.Text,
    'advancedRiskSettings' : AdvancedRiskSettings,
    'strategies' : IDL.Vec(Strategy),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateCandles' : IDL.Func([IDL.Text, IDL.Vec(Candle)], [], []),
    'addPair' : IDL.Func(
        [IDL.Text, IDL.Variant({ 'forex' : IDL.Null, 'crypto' : IDL.Null })],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'fetchBinanceData' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandles' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Vec(Candle)], ['query']),
    'getLatestTradeEntries' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Opt(Trade)))],
        ['query'],
      ),
    'getPairs' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Text,
              IDL.Record({
                'type' : IDL.Variant({
                  'forex' : IDL.Null,
                  'crypto' : IDL.Null,
                }),
                'symbol' : IDL.Text,
              }),
            )
          ),
        ],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [IDL.Opt(ExtendedProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'receiveMT5Candles' : IDL.Func([IDL.Text, IDL.Vec(Candle)], [], []),
    'removePair' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProfile' : IDL.Func([ExtendedProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };