/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdvancedRiskSettings {
  'maxConcurrentTrades' : bigint,
  'maxDailyLoss' : number,
}
export interface Candle {
  'low' : number,
  'high' : number,
  'close' : number,
  'open' : number,
  'volume' : number,
  'timestamp' : bigint,
  'symbol' : string,
}
export interface ExtendedProfile {
  'telegramBotToken' : string,
  'tradingViewData' : Array<TradingViewData>,
  'tradingGoals' : TradingGoals,
  'username' : string,
  'balance' : number,
  'riskPercentage' : number,
  'soundAlertsEnabled' : boolean,
  'telegramChatId' : string,
  'advancedRiskSettings' : AdvancedRiskSettings,
  'strategies' : Array<Strategy>,
}
export type Strategy = { 'scalping' : null } |
  { 'trendFollowing' : null } |
  { 'swing' : null };
export interface Trade {
  'sl' : number,
  'tp' : number,
  'pnl' : number,
  'probability' : bigint,
  'direction' : { 'buy' : null } |
    { 'sell' : null },
  'entry' : number,
  'rrRatio' : number,
  'timestamp' : bigint,
  'outcome' : { 'win' : null } |
    { 'pending' : null } |
    { 'loss' : null },
  'lotSize' : number,
  'symbol' : string,
}
export interface TradingGoals {
  'monthlyProfit' : number,
  'dailyProfit' : number,
}
export interface TradingViewData { 'value' : string, 'indicator' : string }
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'telegramBotToken' : string,
  'balance' : number,
  'dailyProfitTarget' : number,
  'maxRiskPercent' : number,
  'soundAlertsEnabled' : boolean,
  'telegramChatId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateCandles' : ActorMethod<[string, Array<Candle>], undefined>,
  'addPair' : ActorMethod<
    [string, { 'forex' : null } | { 'crypto' : null }],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'fetchBinanceData' : ActorMethod<[string, string], string>,
  'fetchNewsData' : ActorMethod<[string], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandles' : ActorMethod<[string, bigint], Array<Candle>>,
  'getLatestTradeEntries' : ActorMethod<[], Array<[string, [] | [Trade]]>>,
  'getPairs' : ActorMethod<
    [],
    Array<
      [
        string,
        {
          'type' : { 'forex' : null } |
            { 'crypto' : null },
          'symbol' : string,
        },
      ]
    >
  >,
  'getProfile' : ActorMethod<[], [] | [ExtendedProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'receiveMT5Candles' : ActorMethod<[string, Array<Candle>], undefined>,
  'removePair' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProfile' : ActorMethod<[ExtendedProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];