/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TradingGoals {
    monthlyProfit: number;
    dailyProfit: number;
}
export interface AdvancedRiskSettings {
    maxConcurrentTrades: bigint;
    maxDailyLoss: number;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Trade {
    sl: number;
    tp: number;
    pnl: number;
    probability: bigint;
    direction: Variant_buy_sell;
    entry: number;
    rrRatio: number;
    timestamp: bigint;
    outcome: Variant_win_pending_loss;
    lotSize: number;
    symbol: string;
}
export interface Candle {
    low: number;
    high: number;
    close: number;
    open: number;
    volume: number;
    timestamp: bigint;
    symbol: string;
}
export interface ExtendedProfile {
    telegramBotToken: string;
    tradingViewData: Array<TradingViewData>;
    tradingGoals: TradingGoals;
    username: string;
    balance: number;
    riskPercentage: number;
    soundAlertsEnabled: boolean;
    telegramChatId: string;
    advancedRiskSettings: AdvancedRiskSettings;
    strategies: Array<Strategy>;
}
export interface TradingViewData {
    value: string;
    indicator: string;
}
export interface UserProfile {
    telegramBotToken: string;
    balance: number;
    dailyProfitTarget: number;
    maxRiskPercent: number;
    soundAlertsEnabled: boolean;
    telegramChatId: string;
}
export interface http_header {
    value: string;
    name: string;
}
export enum Strategy {
    scalping = "scalping",
    trendFollowing = "trendFollowing",
    swing = "swing"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_buy_sell {
    buy = "buy",
    sell = "sell"
}
export enum Variant_forex_crypto {
    forex = "forex",
    crypto = "crypto"
}
export enum Variant_win_pending_loss {
    win = "win",
    pending = "pending",
    loss = "loss"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addOrUpdateCandles(symbol: string, newCandles: Array<Candle>): Promise<void>;
    addPair(symbol: string, type: Variant_forex_crypto): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    fetchBinanceData(symbol: string, interval: string): Promise<string>;
    fetchNewsData(currencies: string): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCandles(symbol: string, limit: bigint): Promise<Array<Candle>>;
    getLatestTradeEntries(): Promise<Array<[string, Trade | null]>>;
    getPairs(): Promise<Array<[string, {
            type: Variant_forex_crypto;
            symbol: string;
        }]>>;
    getProfile(): Promise<ExtendedProfile | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    receiveMT5Candles(symbol: string, newCandles: Array<Candle>): Promise<void>;
    removePair(symbol: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveProfile(profile: ExtendedProfile): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { AdvancedRiskSettings as _AdvancedRiskSettings, ExtendedProfile as _ExtendedProfile, Strategy as _Strategy, Trade as _Trade, TradingGoals as _TradingGoals, TradingViewData as _TradingViewData, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addOrUpdateCandles(arg0: string, arg1: Array<Candle>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateCandles(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateCandles(arg0, arg1);
            return result;
        }
    }
    async addPair(arg0: string, arg1: Variant_forex_crypto): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPair(arg0, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPair(arg0, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async fetchBinanceData(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchBinanceData(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchBinanceData(arg0, arg1);
            return result;
        }
    }
    async fetchNewsData(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchNewsData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchNewsData(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandles(arg0: string, arg1: bigint): Promise<Array<Candle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandles(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandles(arg0, arg1);
            return result;
        }
    }
    async getLatestTradeEntries(): Promise<Array<[string, Trade | null]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestTradeEntries();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestTradeEntries();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPairs(): Promise<Array<[string, {
            type: Variant_forex_crypto;
            symbol: string;
        }]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPairs();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPairs();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<ExtendedProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async receiveMT5Candles(arg0: string, arg1: Array<Candle>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.receiveMT5Candles(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.receiveMT5Candles(arg0, arg1);
            return result;
        }
    }
    async removePair(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePair(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePair(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveProfile(arg0: ExtendedProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProfile(to_candid_ExtendedProfile_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProfile(to_candid_ExtendedProfile_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_ExtendedProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExtendedProfile): ExtendedProfile {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Strategy_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Strategy): Strategy {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Trade_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trade): Trade {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExtendedProfile]): ExtendedProfile | null {
    return value.length === 0 ? null : from_candid_ExtendedProfile_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Trade]): Trade | null {
    return value.length === 0 ? null : from_candid_Trade_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sl: number;
    tp: number;
    pnl: number;
    probability: bigint;
    direction: {
        buy: null;
    } | {
        sell: null;
    };
    entry: number;
    rrRatio: number;
    timestamp: bigint;
    outcome: {
        win: null;
    } | {
        pending: null;
    } | {
        loss: null;
    };
    lotSize: number;
    symbol: string;
}): {
    sl: number;
    tp: number;
    pnl: number;
    probability: bigint;
    direction: Variant_buy_sell;
    entry: number;
    rrRatio: number;
    timestamp: bigint;
    outcome: Variant_win_pending_loss;
    lotSize: number;
    symbol: string;
} {
    return {
        sl: value.sl,
        tp: value.tp,
        pnl: value.pnl,
        probability: value.probability,
        direction: from_candid_variant_n12(_uploadFile, _downloadFile, value.direction),
        entry: value.entry,
        rrRatio: value.rrRatio,
        timestamp: value.timestamp,
        outcome: from_candid_variant_n13(_uploadFile, _downloadFile, value.outcome),
        lotSize: value.lotSize,
        symbol: value.symbol
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    type: {
        forex: null;
    } | {
        crypto: null;
    };
    symbol: string;
}): {
    type: Variant_forex_crypto;
    symbol: string;
} {
    return {
        type: from_candid_variant_n17(_uploadFile, _downloadFile, value.type),
        symbol: value.symbol
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    telegramBotToken: string;
    tradingViewData: Array<_TradingViewData>;
    tradingGoals: _TradingGoals;
    username: string;
    balance: number;
    riskPercentage: number;
    soundAlertsEnabled: boolean;
    telegramChatId: string;
    advancedRiskSettings: _AdvancedRiskSettings;
    strategies: Array<_Strategy>;
}): {
    telegramBotToken: string;
    tradingViewData: Array<TradingViewData>;
    tradingGoals: TradingGoals;
    username: string;
    balance: number;
    riskPercentage: number;
    soundAlertsEnabled: boolean;
    telegramChatId: string;
    advancedRiskSettings: AdvancedRiskSettings;
    strategies: Array<Strategy>;
} {
    return {
        telegramBotToken: value.telegramBotToken,
        tradingViewData: value.tradingViewData,
        tradingGoals: value.tradingGoals,
        username: value.username,
        balance: value.balance,
        riskPercentage: value.riskPercentage,
        soundAlertsEnabled: value.soundAlertsEnabled,
        telegramChatId: value.telegramChatId,
        advancedRiskSettings: value.advancedRiskSettings,
        strategies: from_candid_vec_n21(_uploadFile, _downloadFile, value.strategies)
    };
}
function from_candid_tuple_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, {
        type: {
            forex: null;
        } | {
            crypto: null;
        };
        symbol: string;
    }]): [string, {
        type: Variant_forex_crypto;
        symbol: string;
    }] {
    return [
        value[0],
        from_candid_record_n16(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, [] | [_Trade]]): [string, Trade | null] {
    return [
        value[0],
        from_candid_opt_n9(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): Variant_buy_sell {
    return "buy" in value ? Variant_buy_sell.buy : "sell" in value ? Variant_buy_sell.sell : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    win: null;
} | {
    pending: null;
} | {
    loss: null;
}): Variant_win_pending_loss {
    return "win" in value ? Variant_win_pending_loss.win : "pending" in value ? Variant_win_pending_loss.pending : "loss" in value ? Variant_win_pending_loss.loss : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    forex: null;
} | {
    crypto: null;
}): Variant_forex_crypto {
    return "forex" in value ? Variant_forex_crypto.forex : "crypto" in value ? Variant_forex_crypto.crypto : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scalping: null;
} | {
    trendFollowing: null;
} | {
    swing: null;
}): Strategy {
    return "scalping" in value ? Strategy.scalping : "trendFollowing" in value ? Strategy.trendFollowing : "swing" in value ? Strategy.swing : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, {
        type: {
            forex: null;
        } | {
            crypto: null;
        };
        symbol: string;
    }]>): Array<[string, {
        type: Variant_forex_crypto;
        symbol: string;
    }]> {
    return value.map((x)=>from_candid_tuple_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Strategy>): Array<Strategy> {
    return value.map((x)=>from_candid_Strategy_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, [] | [_Trade]]>): Array<[string, Trade | null]> {
    return value.map((x)=>from_candid_tuple_n8(_uploadFile, _downloadFile, x));
}
function to_candid_ExtendedProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExtendedProfile): _ExtendedProfile {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_Strategy_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Strategy): _Strategy {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    telegramBotToken: string;
    tradingViewData: Array<TradingViewData>;
    tradingGoals: TradingGoals;
    username: string;
    balance: number;
    riskPercentage: number;
    soundAlertsEnabled: boolean;
    telegramChatId: string;
    advancedRiskSettings: AdvancedRiskSettings;
    strategies: Array<Strategy>;
}): {
    telegramBotToken: string;
    tradingViewData: Array<_TradingViewData>;
    tradingGoals: _TradingGoals;
    username: string;
    balance: number;
    riskPercentage: number;
    soundAlertsEnabled: boolean;
    telegramChatId: string;
    advancedRiskSettings: _AdvancedRiskSettings;
    strategies: Array<_Strategy>;
} {
    return {
        telegramBotToken: value.telegramBotToken,
        tradingViewData: value.tradingViewData,
        tradingGoals: value.tradingGoals,
        username: value.username,
        balance: value.balance,
        riskPercentage: value.riskPercentage,
        soundAlertsEnabled: value.soundAlertsEnabled,
        telegramChatId: value.telegramChatId,
        advancedRiskSettings: value.advancedRiskSettings,
        strategies: to_candid_vec_n26(_uploadFile, _downloadFile, value.strategies)
    };
}
function to_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_forex_crypto): {
    forex: null;
} | {
    crypto: null;
} {
    return value == Variant_forex_crypto.forex ? {
        forex: null
    } : value == Variant_forex_crypto.crypto ? {
        crypto: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Strategy): {
    scalping: null;
} | {
    trendFollowing: null;
} | {
    swing: null;
} {
    return value == Strategy.scalping ? {
        scalping: null
    } : value == Strategy.trendFollowing ? {
        trendFollowing: null
    } : value == Strategy.swing ? {
        swing: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Strategy>): Array<_Strategy> {
    return value.map((x)=>to_candid_Strategy_n27(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
